name: Compile arm64

on:
  push:
    branches: [ "main" ]

env:
  ANDROID_ABI: arm64-v8a
  OPENSSL_VERSION: 3.0.1
  ANDROID_NDK_VERSION: r25
  ANDROID_TARGET_API: 31

jobs:
  compile_arm64:
    name: Compile arm64-v8a
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Install aria2
        run: |
          sudo apt -yqq update
          sudo apt install -yqq aria2
      
      - name: Download Android NDK
        id: download_ndk
        run: |
          aria2c https://dl.google.com/android/repository/android-ndk-${{env.ANDROID_NDK_VERSION}}-linux.zip
          unzip android-ndk-${{env.ANDROID_NDK_VERSION}}-linux.zip
          echo "::set-output name=status::success"

      - name: Download OpenSSL
        id: download_openssl
        if: steps.download_ndk.outputs.status == 'success' && !cancelled()
        run: |
          aria2c https://www.openssl.org/source/openssl-${{env.OPENSSL_VERSION}}.tar.gz
          tar -zxvf openssl-${{env.OPENSSL_VERSION}}.tar.gz
          echo "::set-output name=status::success"

      - name: Compile
        id: compile
        if: steps.download_openssl.outputs.status == 'success' && !cancelled()
        run: |
          echo "${{github.workspace}}/android-ndk-${{env.ANDROID_NDK_VERSION}}-linux" >> $ANDROID_NDK_ROOT
          cd openssl-${{env.OPENSSL_VERSION}}
          PATH=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin:$ANDROID_NDK_ROOT/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin:$ANDROID_NDK_ROOT/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin:$PATH
          ./Configure android-arm64 -D__ANDROID_API__=${{env.ANDROID_TARGET_API}} -static no-ssl3 no-comp no-engine no-shared no-tests --prefix=${{github.workspace}}/output
          echo "::set-output name=status::success"