name: Compile arm64

on:
  push:
    branches: [ "main" ]

env:
  ANDROID_ABI: arm64-v8a
  OPENSSL_VERSION: 3.0.1
  ANDROID_NDK_VERSION: r25
  ANDROID_TARGET_API: 31

jobs:
  compile_arm64:
    name: Compile arm64-v8a
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Install aria2
        run: |
          sudo apt -yqq update
          sudo apt install -yqq aria2
      
      - name: Download Android NDK
        id: download_ndk
        run: |
          aria2c https://dl.google.com/android/repository/android-ndk-${{env.ANDROID_NDK_VERSION}}-linux.zip
          unzip android-ndk-${{env.ANDROID_NDK_VERSION}}-linux.zip
          echo "::set-output name=status::success"

      - name: Download OpenSSL
        id: download_openssl
        if: steps.download_ndk.outputs.status == 'success' && !cancelled()
        run: |
          aria2c https://www.openssl.org/source/openssl-${{env.OPENSSL_VERSION}}.tar.gz
          tar -zxvf openssl-${{env.OPENSSL_VERSION}}.tar.gz
          echo "::set-output name=status::success"

      - name: Compile
        id: compile
        if: steps.download_openssl.outputs.status == 'success' && !cancelled()
        run: |
          cd openssl-${{env.OPENSSL_VERSION}}
          bash ./build_arm64.sh ${{github.workspace}}/android-ndk-${{env.ANDROID_NDK_VERSION}}-linux ${{env.ANDROID_TARGET_API}} ${{github.workspace}}/output
          echo "::set-output name=status::success"